name: Compile and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Use the Node.js version you prefer

    - name: Install dependencies
      run: npm install

    - name: Build (if needed)
      run: |
        # Your build commands here.
        # For example, if you were using TypeScript, you might use:
        # npm run tsc
        echo "Build completed"

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v0.2.1
        release_name: v0.2.1
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path-to-your-compiled-file-or-archive.zip
        asset_name: compiled-code.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
